version: "3.1"

services:
    postgres:
        container_name: tasks_shadow
        image: postgres:latest
        environment:
            POSTGRES_USER: shadow
            POSTGRES_PASSWORD: shadow
            POSTGRES_DB: shadow
        ports:
            - "5433:5432"

    postgres2:
        container_name: tasks
        image: postgres:latest
        environment:
            POSTGRES_USER: tasks
            POSTGRES_PASSWORD: tasks
            POSTGRES_DB: tasks
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
